pipeline {
    agent any
    parameters {
        string(name: 'REQUESTED_ACTION', defaultValue: '', description: 'type the action')
    }
    stages {
        stage ('build') {

              when {
                  expression {params.REQUESTED_ACTION == 'greetings'}
              }
            steps {
                echo "Building"
            }
            
          }
        stage('test') {
            when {
                expression {${BRANCH_NAME} == 'feature'}
            }
            steps {
                echo "testing"
            }
        }
    }
}